version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile 
    container_name: ruby-sinatra
    command: ruby ./server.rb -o 0.0.0.0 -p 80
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
